### ISSUE TITLE
Google Classroom and complete migration to GApps Suite

### ISSUE THREAD

**Issue by TheOneKevin** [petcsclub/petcsclub.github.io#2]
Deadline: Before first club meeting

**Comment by redapple410** [comment]
Google classroom has been created. I will close this task once we've made 1 or 2 introductory posts.

**Comment by albertlai431** [comment]
@TheCool1Kevin @redapple410 I think this is good to close now? Unless our files need to be migrated too?

**Comment by TheOneKevin** [comment]
Yeah
