### ISSUE TITLE
Make Posters by Sept 16

### ISSUE THREAD

**Issue by albertlai431** [petcsclub/petcsclub.github.io#5]
Kevin - make posters (with help from Owen)
Albert - manage communications

Tentative due date of September 16

**Comment by albertlai431** [comment]
@TheCool1Kevin I emailed trudeau sac on the process of getting posters approved, will let you know when we get a reply

**Comment by TheOneKevin** [comment]
The 8 posters are on Drive. Albert will be printing them and they'll be posted by this afternoon.
