### ISSUE TITLE
First Meeting on Sept 16 After School

### ISSUE THREAD

**Issue by albertlai431** [petcsclub/petcsclub.github.io#6]
We will be meeting afterschool next Monday to primarily discuss our first club meeting, as well as club PR and clubs week. 

For now, just brainstorm what you would like to see at the orientation and keep a few ideas in mind :)

**Comment by TheOneKevin** [comment]
@albertlai431 please update to be in compliance with the new “Admin reminders” template. Thanks :)

**Comment by albertlai431** [comment]
@TheCool1Kevin wait sorry, I'm confused lol, what am I supposed to do?

**Comment by TheOneKevin** [comment]
@albertlai431 dw abt it, I just wanted to test out the comment system lol. But if you go create a new Issue, you should see the templates
