### ISSUE TITLE
Decide on application to HackClub by Sept. 13

### ISSUE THREAD

**Issue by TheOneKevin** [petcsclub/petcsclub.github.io#7]
**Deadline (required):** Sept. 13

As suggested by @albertlai431 

If yes, we need to create an account and apply. See: https://hackclub.com/

**Comment by albertlai431** [comment]
Applications look pretty long and competitive - unless @TheCool1Kevin and @redapple410 have lots of time in the next 2 days (since I'll be super busy) and are willing to work on the apps, we probably shouldn't do it

**Comment by TheOneKevin** [comment]
All core execs have submitted personal profile and club profiles. Application is now submitted.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheOneKevin** [comment]
Results will be sent in 1 week

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
